### ISSUE TITLE
依存性が解決されない

### ISSUE THREAD

**Issue by ryo0ka** [hexx/fujitask-simple#2]
SBT v0.13.9でプロジェクトをそのまま読み込んでいるのですが、外部ライブラリへの依存性が全滅です。あまり詳しくないのでこちらで何か取りこぼしているのかもしれませんが、そちらで試していただけるでしょうか。

**Comment by xuwei-k** [comment]
普通に依存解決出来る気がする

**Comment by ryo0ka** [comment]
改めて試したところ普通に通りました。原因は分からないですが。。
どうもご迷惑をおかけしました。
